# Generated by Django 3.0.8 on 2020-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('image', models.URLField(blank=True, verbose_name='Url da Imagem do Produto')),
                ('brand', models.CharField(max_length=254, verbose_name='Marca do Produto')),
                ('title', models.CharField(max_length=254, verbose_name='Titulo')),
                ('review_score', models.IntegerField(default=0, verbose_name='Review do Produto')),
            ],
        ),
    ]
